services:
  analysis-env:
    image: tiffgong/dockerfile-practice
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/pizza
    environment:
      PASSWORD: "password"
      DISABLE_AUTH: true